---
# tasks for rpi_expandfs role

# DEPENDENCIES
- name: "[Debian] Include Debian dependencies installation tasks"
  include_tasks: dependencies.yml
  when: ansible_os_family == 'Debian'
  tags:
  - rpi_expandfs
  - rpi_expandfs_dependencies

# OS-SPECIFIC TASKS
- name: "[main] Include tasks from {{ ansible_os_family }}.yml"
  include_tasks: "{{ ansible_os_family }}.yml"
  tags: rpi_expandfs

- meta: flush_handlers
  tags: rpi_expandfs
